### ISSUE TITLE
嘿，很喜欢这个包，请问如何对消息进行细分

### ISSUE THREAD

**Issue by yizenghui** [KevinGong2013/wechat#1]
如，朋友给我分享链接，我如何去获得其中的 title pic description 等参数
如果订阅的公众号推送消息，我如何去获得相应的内容
作者大大有考虑对此进行细分吗？
十分感谢

**Comment by KevinGong2013** [comment]
订阅`msg`可以拿到所有的消息，然后根据`msgtype`区分不同的链接，推送消息直接解析消息题就可以了
```
bot.Handle(`/msg`, func(evt wechat.Event) {
		logger.Debug(`begin handle [/msg]`)
		data := evt.Data.(wechat.EventMsgData)
	})
```

**Comment by yizenghui** [comment]
嗯，问题已解决。 我已经参考作者另一个项目 ggbot 去处理了(实际最终用正则匹配data.Content)。
